[config]
keep_std = true

[game_list]
"com.example" = [30, 60, 90, 120, 144, 165, 180, 240]

[powersave]
margin_fps = 3.0
core_temp_thresh = "disabled"

[balance]
margin_fps = 1.0
core_temp_thresh = "disabled"

[performance]
margin_fps = 0.3
core_temp_thresh = "disabled"

[fast]
margin_fps = 0
core_temp_thresh = "disabled"
